[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "onto-mcp-server"
version = "0.1.0"
description = "A FastMCP server for Onto resources."

[tool.setuptools]
packages = ["onto_mcp"]
