name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -r requirements.txt
      - name: Run unit tests
        run: pytest tests/ -v --tb=short -k "not interactive"
      - name: Run unit tests from main package
        run: pytest test_keycloak_auth.py -v --tb=short -k "not interactive"
